### ISSUE TITLE
Refatorar código de coleta de IDs baseado em estratégia

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#283]
Refatorar código de coleta de IDs a partir do Solr baseado em estratégia.
O processo atual está não esta conseguindo realizar a coleta para resultados de pesquisa com muitos "hits".

Erro:

```
Traceback (most recent call last):
  File "../tpl/coleta-IDs_portal.py", line 125, in <module>
    r_range = requests.post(url, data=payload, headers=header, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='bases.bireme.br', port=8986): Max retries exceeded with url: /solr5/portal/select/ (Caused by <class 'httplib.BadStatusLine'>: '')

```

**Comment by falbrito** [comment]
O processo foi alterado para que seja calculado o total de "hits", dessa forma quebra-se o número de solicitações ao servidor Solr, proporcionando o processamento de execuções em paralelo e assim o término da coleta em menos tempo.

Tempo de execução em Teste:
```
...
...
...
DURACAO DE PROCESSAMENTO
-------------------------------------------------------------------------
 - Inicio:  2020.05.25 01:11:02
 - Termino: 2020.05.25 07:17:49

 Tempo de execucao: 22007 [s]
 Ou 6h 6m 47s

[TIME-STAMP] 2020.05.25 07:17:49 [:FIM:] Processa  ./Coleta_MTCs.sh    

```

Scripts:
```
/bases/Strategies2IAHX/apps/tpl/BaixaIDs.sh
/bases/Strategies2IAHX/apps/tpl/coleta-IDs_portal_particionado.py
/bases/Strategies2IAHX/apps/tpl/descobreTotal.py

```
